/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hpst.java8;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

import org.junit.Test;

public class StreamAlreadyClosedTest {
	
	
	/**
	 * 
	 * java.lang.IllegalStateException: stream has already been operated upon or closed
		at java.util.stream.AbstractPipeline.sourceStageSpliterator(Unknown Source)
		at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
		at com.hpst.java8.StreamAlreadyClosedTest.testStreamAlreadyClosed(StreamAlreadyClosedTest.java:22)
		..
		..


	 */
	
    @Test 
    public void testStreamAlreadyClosed() {
    	List<String> title = Arrays.asList("Java8","In","Action");
    	Stream<String> stream = title.stream();
    	stream.forEach(System.out::println);
    	stream.forEach(System.out::println);
    }
}
